version: "3.5"

services:

  caddy:
    image: "lucaslorentz/caddy-docker-proxy:ci-alpine"
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/caddy/:/data
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=up_proxy_network
    labels:
      caddy: ${LISTEN_DOMAIN}
  proxy:
    image: "unifiedpush/common-proxies"
    labels:
      caddy: ${LISTEN_DOMAIN}
      caddy.@match.path: /generic* /wpfcm* /_matrix*
      caddy.reverse_proxy: "@match {{upstreams 5000}}"
    restart: unless-stopped
    environment:
      - UP_GATEWAY_MATRIX_ENABLE=true
networks:
  default:
    name: up_proxy_network
